import { GITHUB_API, OAUTH_PROXY_URL, REPO_OWNER, REPO_NAME, DATA_DIR } from './constants';

function toBase64(str) {
  const bytes = new TextEncoder().encode(str);
  const binString = Array.from(bytes, (byte) => String.fromCodePoint(byte)).join('');
  return btoa(binString);
}

export class GitHubService {
  constructor(token) {
    this.token = token;
    this.headers = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    };
  }

  async request(url, options = {}) {
    const res = await fetch(url.startsWith('http') ? url : `${GITHUB_API}${url}`, {
      ...options,
      headers: { ...this.headers, ...options.headers },
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.message || `GitHub API error: ${res.status}`);
    }
    return res.json();
  }

  async getUser() {
    return this.request('/user');
  }

  async getUserProfile(username) {
    try {
      const res = await fetch(
        `${GITHUB_API}/repos/${REPO_OWNER}/${REPO_NAME}/contents/${DATA_DIR}/${username}.json`,
        { headers: { Accept: 'application/vnd.github.v3+json' } }
      );
      if (!res.ok) return null;
      const data = await res.json();
      return JSON.parse(atob(data.content));
    } catch {
      return null;
    }
  }

  async listProfiles() {
    try {
      const res = await fetch(
        `${GITHUB_API}/repos/${REPO_OWNER}/${REPO_NAME}/contents/${DATA_DIR}`,
        { headers: { Accept: 'application/vnd.github.v3+json' } }
      );
      if (!res.ok) return [];
      const files = await res.json();
      return files
        .filter((f) => f.name.endsWith('.json'))
        .map((f) => f.name.replace('.json', ''));
    } catch {
      return [];
    }
  }

  async checkWriteAccess() {
    try {
      const repo = await this.request(`/repos/${REPO_OWNER}/${REPO_NAME}`);
      return repo.permissions?.push || repo.permissions?.admin || false;
    } catch {
      return false;
    }
  }

  async ensureFork() {
    const user = await this.getUser();
    try {
      const existing = await this.request(`/repos/${user.login}/${REPO_NAME}`);
      if (existing.fork) return existing;
    } catch { /* no fork yet */ }

    const fork = await this.request(`/repos/${REPO_OWNER}/${REPO_NAME}/forks`, {
      method: 'POST',
      body: JSON.stringify({ default_branch_only: true }),
    });

    await new Promise((r) => setTimeout(r, 4000));
    return fork;
  }

  async getDefaultBranchSha(repoFullName) {
    const ref = await this.request(`/repos/${repoFullName}/git/ref/heads/main`);
    return ref.object.sha;
  }

  async createBranch(repoFullName, branchName, sha) {
    try {
      await this.request(`/repos/${repoFullName}/git/refs`, {
        method: 'POST',
        body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha }),
      });
    } catch {
      // Branch already exists — delete it and recreate fresh at current main SHA
      try {
        await this.request(`/repos/${repoFullName}/git/refs/heads/${branchName}`, {
          method: 'DELETE',
        });
      } catch { /* ignore deletion errors */ }
      await this.request(`/repos/${repoFullName}/git/refs`, {
        method: 'POST',
        body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha }),
      });
    }
  }

  async getFileSha(repoFullName, path, branch) {
    try {
      const res = await fetch(
        `${GITHUB_API}/repos/${repoFullName}/contents/${path}?ref=${branch}`,
        { headers: this.headers }
      );
      if (!res.ok) return null;
      const data = await res.json();
      return data.sha;
    } catch {
      return null;
    }
  }

  async commitFile(repoFullName, path, content, branch, message) {
    const sha = await this.getFileSha(repoFullName, path, branch);
    const body = {
      message,
      content: toBase64(JSON.stringify(content, null, 2)),
      branch,
    };
    if (sha) body.sha = sha;

    return this.request(`/repos/${repoFullName}/contents/${path}`, {
      method: 'PUT',
      body: JSON.stringify(body),
    });
  }

  async createPullRequest(username, head, branchName) {
    const headRef = head === REPO_OWNER ? branchName : `${head}:${branchName}`;
    try {
      const pulls = await this.request(
        `/repos/${REPO_OWNER}/${REPO_NAME}/pulls?head=${headRef}&state=open`
      );
      if (pulls.length > 0) return pulls[0];
    } catch { /* no existing PR */ }

    return this.request(`/repos/${REPO_OWNER}/${REPO_NAME}/pulls`, {
      method: 'POST',
      body: JSON.stringify({
        title: `[RigTree] Add/update profile: ${username}`,
        head: headRef,
        base: 'main',
        body: `## RigTree Profile Update\n\nAutomated PR from the RigTree app.\n\n**User:** @${username}\n**Action:** Profile create/update\n\n---\n*This PR was generated by [RigTree](https://${window.location.host}).*`,
      }),
    });
  }

  async submitProfile(profileData) {
    const username = profileData.username;
    const branchName = `rigtree/${username}`;
    const filePath = `${DATA_DIR}/${username}.json`;
    const data = { ...profileData, last_updated: new Date().toISOString() };

    const hasWriteAccess = await this.checkWriteAccess();

    if (hasWriteAccess) {
      const targetRepo = `${REPO_OWNER}/${REPO_NAME}`;
      const mainSha = await this.getDefaultBranchSha(targetRepo);
      await this.createBranch(targetRepo, branchName, mainSha);
      await this.commitFile(targetRepo, filePath, data, branchName, `Update RigTree profile for ${username}`);
      return await this.createPullRequest(username, REPO_OWNER, branchName);
    }

    const fork = await this.ensureFork();
    const mainSha = await this.getDefaultBranchSha(fork.full_name);
    await this.createBranch(fork.full_name, branchName, mainSha);
    await this.commitFile(fork.full_name, filePath, data, branchName, `Update RigTree profile for ${username}`);
    return await this.createPullRequest(username, fork.owner.login, branchName);
  }
}

export async function exchangeCodeForToken(code) {
  if (!OAUTH_PROXY_URL) {
    throw new Error('OAuth proxy is not configured. Set VITE_OAUTH_PROXY_URL in your environment.');
  }
  const res = await fetch(OAUTH_PROXY_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ code }),
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(data.error || `Failed to exchange code for token (${res.status})`);
  }
  return data.access_token;
}
