name = "rigtree-oauth"
main = "oauth-proxy.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "https://rigtree.pages.dev"


[[kv_namespaces]]
binding = "SESSIONS"
id = "0148fc56b16243fdb7f3a7bf4793643d"
